server:
  port: 8084
spring:
  application:
    name: good-web
  thymeleaf:
    cache: false  #关闭模板缓存，不然修改了会看不到
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.109.139
    port: 5672
    virtual-host: /xiaohong
    username: xiaohong
    password: xiaohong
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5  #微服务拉取时间
    eureka-connection-idle-timeout-seconds: 10 #心跳时间