server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.109.139
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10  #拉取服务的时间
  instance:
    lease-expiration-duration-in-seconds: 15  #过期时间
    lease-renewal-interval-in-seconds: 5  #心跳时间
leyou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN